# Generated by Django 4.2 on 2023-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_imgae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imgae',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_pics'),
        ),
    ]
